import React from "react";

const About = () => {
  return(  <div className="container"
  style={{height:"100vh"}}>About
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas voluptatum, repudiandae molestiae nulla dolores enim recusandae in quos culpa doloremque aspernatur, tempore dolorum iste nisi provident beatae. Commodi aliquam voluptas laudantium! Dolorem necessitatibus cumque officiis ullam nostrum exercitationem voluptate eveniet, in et tempore quae pariatur odit modi ipsa corporis, at ab deserunt? Qui mollitia, odit atque delectus incidunt tenetur temporibus quisquam! Pariatur, maxime? Repellendus illum adipisci, nesciunt consequuntur atque nostrum iste iure doloremque qui labore eos. Fuga tenetur qui sunt possimus fugit officiis incidunt architecto error delectus excepturi, itaque dolorem molestias voluptas laborum accusamus praesentium similique, rerum saepe corporis, veritatis voluptates molestiae! Quis sapiente molestiae libero asperiores enim, consequuntur ipsam ut quasi odit quae ad non explicabo commodi. Minus amet nihil officia dolore voluptates dignissimos atque sapiente repellat, neque natus repudiandae minima a ullam earum.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, tempora eaque nobis amet dicta, omnis corporis officiis alias, asperiores neque iusto. Repudiandae voluptatem veritatis nam, impedit officiis est quasi ab dignissimos voluptates magni laudantium dolorem cupiditate temporibus eum debitis quas deserunt pariatur odit sed corporis. Magni dolores repudiandae consequatur illum itaque, reprehenderit quia vel dolor? Quaerat aperiam libero ad repudiandae officia assumenda perspiciatis enim, cum ratione eos suscipit incidunt ipsum minus quisquam perferendis quae nam, quibusdam nisi dolores obcaecati. Illo, quam accusantium reprehenderit temporibus, dicta laudantium consequuntur sapiente pariatur doloremque cumque quibusdam earum. Sequi, ab eum blanditiis nemo accusamus delectus, libero et vel nisi beatae, veritatis asperiores ducimus accusantium! Laboriosam repellat nisi, animi a quae in reiciendis. Excepturi vel quibusdam at expedita magni sint omnis ipsum dicta commodi est laudantium illum culpa unde reprehenderit modi temporibus, fuga reiciendis suscipit labore ex! Magni deleniti explicabo minima ut? Recusandae, accusamus! Esse, obcaecati in aliquam facere dicta totam. Blanditiis totam ab nihil eaque magni qui corporis eius, nam veniam! Ad amet, nam odio hic dolore exercitationem delectus officiis quasi quibusdam impedit optio tempore eligendi numquam accusantium quo quae accusamus modi quos. Praesentium asperiores temporibus laborum iusto numquam quaerat libero laboriosam facere enim, expedita magni eum! Quia error odio iusto, eaque quidem nulla asperiores in numquam ea cumque. Ipsa, aliquid qui est recusandae quam odio necessitatibus neque possimus, culpa voluptate labore inventore earum ab reprehenderit id rem cumque velit amet corrupti. Reiciendis minus sit iste perferendis suscipit voluptatem necessitatibus hic velit facere commodi?
  </div>
  )
};

export default About;
